language: java
jdk: oraclejdk8
notifications:
  email: false
env:
  global:
  - TERM=dumb

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

branches:
  except:
  - /^release-.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew curseforge -S
    on:
      all_branches: true
      repo: CyclopsMC/CapabilityProxy
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: AxBezC+z/BOoLAciP46FAGEwmAW6IkydEMD+wrQgiso25KILuh5eNqAWJsb/VkLKEX8QD93c1igjDH03s166uIMQaJ5YluXQZpuH0cEQXeEnGj9MM7UoSGaCNnCvvq2jXQFT3IsuI7Lwged97ZZ2Nt3Kq3ruUBy3mOqE4IrIoPdC7SGD0w81JeOF6IUtmcFvE2gEWMEvRb8ZOTtd4nC3U1MBOAezPwOVCIRo6fOXIkU51hFnvieogN47AoVCGjQYLl4FbNVkRE8VSCb7036NNfM/BWYxhImyjyqyN9KWGukPe4FiWuVTNuURGXEHjcQQu5he1+eruJR3M3i4DOUbxYZljhjjm18E1xA0oxt5SxXx+10iEZ7+xb0zPZOFlb0u010RKNREAHE6Cx9WWDRZjDy7nrKNbonCynh1AibnTpS0yAB1+ynxQsi6s/rgi+k4N7EJJfBrcuUbDAYWmJA9+f5o2ouk4CSvrCmGQXtVGRurmCsEZeVPcJ6Aw77KmwHYZyC2hIe1npkt7Gz4BLWB3z9VK7QMS5FUijmXxKgCK54c6OaPBsOsTyL368myIJJKhscD0oyAXJnYWdbV5sdtJMpodcClxMq70YGJEZSrisLBoWTy0p9FsIq8I+yHp/6oO92jTXTzaDgRXSnibKj9fN8Rd14fpzdYEX4fEZKu6dU=
    on:
      all_branches: true
      repo: CyclopsMC/CapabilityProxy
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: CyclopsMC/CapabilityProxy
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
